/*CREATE TABLE PAYMENT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PAYMENT_ID VARCHAR(20) NOT NULL,
    PAYMENT_METHOD VARCHAR(100) NOT NULL,
    CARD_NO VARCHAR(20) NOT NULL,
    CVC VARCHAR(3) NOT NULL,
    EXPIRED_PERIOD VARCHAR(4) NOT NULL,
    INSTALLMENT_MONTH INT NOT NULL,
    CANCEL_PAYMENT_ID VARCHAR(20),
    AMOUNT BIGINT NOT NULL,
    ENC_PAYMENT_INFO VARCHAR(300) NOT NULL,
    ETC VARCHAR(47) NOT NULL,
    UNIQUE KEY IDX_PAYMENT (PAYMENT_ID)
);

CREATE TABLE CANCEL_PAYMENT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PAYMENT_ID VARCHAR(20) NOT NULL,
    CANCEL_PAYMENT_ID VARCHAR(20) NOT NULL,
    UNIQUE KEY IDX_CANCEL_PAYMENT (CANCEL_PAYMENT_ID)
);
*/